package menuOptions;

public enum StaffMenuOptions {

	EXIT_MENU,
	CREATE_ATTENDEE,
	EDIT_ATTENDEE,
	DELETE_ATTENDEE,
	CREATE_BOOKING,
	EDIT_BOOKING,
	DELETE_BOOKING,
	BOOKING_COST,
	LIST_BOOKING_ATTENDEES,
	SEARCH,
	CREATE_TABLES,
	DROP_TABLES,
	SET_PRICES,
	GET_PRICES
	
}
